---
- name: Install and setup k9s
  hosts: control-plane
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Create k9s directory
      file:
        path: /tmp/k9s
        state: directory
      become: true

    - name: Download k9s
      get_url:
        url: https://github.com/derailed/k9s/releases/download/v0.27.4/k9s_Linux_amd64.tar.gz
        dest: /tmp/k9s/k9s.tar.gz
      become: true

    - name: Extract k9s archive
      unarchive:
        src: /tmp/k9s/k9s.tar.gz
        dest: /tmp/k9s
        remote_src: yes
      become: true

    - name: Move k9s binary to /usr/local/bin
      copy:
        src: /tmp/k9s/k9s
        dest: /usr/local/bin/k9s
        mode: '0755'
        remote_src: yes
      become: true

    - name: Clean up temporary files
      file:
        path: /tmp/k9s
        state: absent
      become: true